
package cz.cvut.kbss.jopa.eswc2016.model.model;

import java.util.Date;
import java.util.Map;
import java.util.Set;
import cz.cvut.kbss.jopa.CommonVocabulary;
import cz.cvut.kbss.jopa.eswc2016.model.Vocabulary;
import cz.cvut.kbss.jopa.model.annotations.*;


/**
 * This class was generated by the OWL2Java tool version 0.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Event)
public class Event {

    @OWLAnnotationProperty(iri = CommonVocabulary.RDFS_LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = CommonVocabulary.DC_DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Id(generated = true)
    protected String id;
    @Properties(fetchType = FetchType.EAGER)
    protected Map<String, Set<String>> properties;

    @Inferred
    @OWLObjectProperty(iri = Vocabulary.s_p_isDocumentedBy)
    protected Set<report> isDocumentedBy;
    @OWLDataProperty(iri = Vocabulary.s_p_date_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_d_dateTime, min = 1, max = 1)
    })
    protected Date date;
    @OWLDataProperty(iri = Vocabulary.s_p_identifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_d__long, min = 1, max = 1)
    })
    protected Long identifier;
    @OWLDataProperty(iri = Vocabulary.s_p_title_A_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_d_string, min = 1, max = 1)
    })
    protected String title;

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    public void setIsDocumentedBy(Set<report> isDocumentedBy) {
        this.isDocumentedBy = isDocumentedBy;
    }

    public Set<report> getIsDocumentedBy() {
        return isDocumentedBy;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Date getDate() {
        return date;
    }

    public void setIdentifier(Long identifier) {
        this.identifier = identifier;
    }

    public Long getIdentifier() {
        return identifier;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitle() {
        return title;
    }

}
