
package cz.cvut.kbss.jopa.eswc2016.model.model;

import cz.cvut.kbss.jopa.CommonVocabulary;
import cz.cvut.kbss.jopa.eswc2016.model.Vocabulary;
import cz.cvut.kbss.jopa.model.annotations.*;

import java.util.Map;
import java.util.Set;


/**
 * This class was generated by the OWL2Java tool version 0.4
 */
@OWLClass(iri = Vocabulary.s_c_logical_record)
public class Record {

    @OWLAnnotationProperty(iri = CommonVocabulary.RDFS_LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = CommonVocabulary.DC_DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Id(generated = true)
    protected String id;
    @Properties
    protected Map<String, Set<String>> properties;
    @OWLObjectProperty(iri = Vocabulary.s_p_has_question, fetch = FetchType.EAGER)
    @ParticipationConstraints({
            @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_question, min = 1, max = 1)
    })
    protected Question has_question;
    @OWLObjectProperty(iri = Vocabulary.s_p_has_answer, fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @ParticipationConstraints({
            @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_answer, min = 1, max = 1)
    })
    protected Answer has_answer;

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    public void setHas_question(Question has_question) {
        this.has_question = has_question;
    }

    public Question getHas_question() {
        return has_question;
    }

    public void setHas_answer(Answer has_answer) {
        this.has_answer = has_answer;
    }

    public Answer getHas_answer() {
        return has_answer;
    }

}
