/**
 * Copyright (C) 2019 Czech Technical University in Prague
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package cz.cvut.kbss.jopa.eswc2016.model;



/**
 * This class was generated by OWL2Java 0.13.1
 * 
 */
public class Vocabulary {

    public final static String ONTOLOGY_IRI_documentation = "http://onto.fel.cvut.cz/ontologies/aviation/documentation";
    public final static String ONTOLOGY_IRI_ufo_b = "http://onto.fel.cvut.cz/ontologies/ufo/ufo-b";
    public final static String ONTOLOGY_IRI_ufo = "http://onto.fel.cvut.cz/ontologies/ufo";
    public final static String ONTOLOGY_IRI_jopa_eswc2016_dot_owl_generated = "http://onto.felk.cvut.cz/ontologies/2016/jopa-eswc2016.owl-generated";
    public final static String ONTOLOGY_IRI_ = "http://xmlns.com/foaf/0.1/";
    public final static String ONTOLOGY_IRI_jopa_eswc2016_dot_owl = "http://onto.felk.cvut.cz/ontologies/2016/jopa-eswc2016.owl";
    public final static String ONTOLOGY_IRI_powertypes = "http://onto.fel.cvut.cz/ontologies/ufo/powertypes";
    public final static String ONTOLOGY_IRI_ufo_a = "http://onto.fel.cvut.cz/ontologies/ufo/ufo-a";
    public final static String s_c_Thing = "http://www.w3.org/2002/07/owl#Thing";
    public final static String s_c_answer = "http://onto.fel.cvut.cz/ontologies/documentation/answer";
    public final static String s_c_logical_record = "http://onto.fel.cvut.cz/ontologies/documentation/logical_record";
    /**
     * Otázka představuje část formuláře, na kterou se očekává vstup od reportéra. Otázka má typ (string, datum, integer, číslo mezi 1 a 5, vyplnění seznamu podotázek atd.).
     * 
     */
    public final static String s_c_question = "http://onto.fel.cvut.cz/ontologies/documentation/question";
    public final static String s_c_report = "http://onto.fel.cvut.cz/ontologies/documentation/report";
    public final static String s_c_Event = "http://onto.fel.cvut.cz/ontologies/ufo/Event";
    public final static String s_c_Person = "http://onto.fel.cvut.cz/ontologies/ufo/Person";
    public final static String s_p_documents = "http://onto.fel.cvut.cz/ontologies/documentation/documents";
    public final static String s_p_hasAuthor = "http://onto.fel.cvut.cz/ontologies/documentation/hasAuthor";
    public final static String s_p_has_documentation_part = "http://onto.fel.cvut.cz/ontologies/documentation/has_documentation_part";
    public final static String s_p_has_question = "http://onto.fel.cvut.cz/ontologies/documentation/has_question";
    public final static String s_p_isDocumentedBy = "http://onto.fel.cvut.cz/ontologies/documentation/isDocumentedBy";
    public final static String s_p_has_answer = "http://onto.fel.cvut.cz/ontologies/documentationy/has_answer";
    public final static String s_p_has_data_value = "http://onto.fel.cvut.cz/ontologies/documentation/has_data_value";
    /**
     * Date of creation of the resource.
     * 
     */
    public final static String s_p_created = "http://purl.org/dc/terms/created";
    /**
     * A point or period of time associated with an event in the lifecycle of the resource.
     * 
     */
    public final static String s_p_date = "http://purl.org/dc/terms/date";
    /**
     * An unambiguous reference to the resource within a given context.
     * 
     */
    public final static String s_p_identifier = "http://purl.org/dc/terms/identifier";
    /**
     * A name given to the resource.
     * 
     */
    public final static String s_p_title = "http://purl.org/dc/terms/title";
    /**
     * Indicates the name (identifier) associated with this online account.
     * 
     */
    public final static String s_p_accountName = "http://xmlns.com/foaf/0.1/accountName";
    /**
     * The first name of a person.
     * 
     */
    public final static String s_p_firstName = "http://xmlns.com/foaf/0.1/firstName";
    /**
     * The last name of a person.
     * 
     */
    public final static String s_p_lastName = "http://xmlns.com/foaf/0.1/lastName";
    public final static String s_p_isIntegrityConstraintFor = "http://krizik.felk.cvut.cz/ontologies/2009/ic.owl#isIntegrityConstraintFor";
    public final static String s_p_javaClassName = "http://krizik.felk.cvut.cz/ontologies/2009/ic.owl#javaClassName";

}
